/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllExercisesResponse18Builder {
    //the instance to build
    private AllExercisesResponse18 allExercisesResponse18;

    /**
     * Default constructor to initialize the instance
     */
    public AllExercisesResponse18Builder() {
        allExercisesResponse18 = new AllExercisesResponse18();
    }

    public AllExercisesResponse18Builder name(String name) {
        allExercisesResponse18.setName(name);
        return this;
    }

    public AllExercisesResponse18Builder caloryCount(String caloryCount) {
        allExercisesResponse18.setCaloryCount(caloryCount);
        return this;
    }

    public AllExercisesResponse18Builder category(String category) {
        allExercisesResponse18.setCategory(category);
        return this;
    }

    public AllExercisesResponse18Builder cardioSubcategory(String cardioSubcategory) {
        allExercisesResponse18.setCardioSubcategory(cardioSubcategory);
        return this;
    }

    public AllExercisesResponse18Builder primaryMuscleGroup(String primaryMuscleGroup) {
        allExercisesResponse18.setPrimaryMuscleGroup(primaryMuscleGroup);
        return this;
    }

    public AllExercisesResponse18Builder exerciseId(String exerciseId) {
        allExercisesResponse18.setExerciseId(exerciseId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllExercisesResponse18 build() {
        return allExercisesResponse18;
    }
}