/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllExercisesResponseBuilder {
    //the instance to build
    private AllExercisesResponse allExercisesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllExercisesResponseBuilder() {
        allExercisesResponse = new AllExercisesResponse();
    }

    public AllExercisesResponseBuilder name(String name) {
        allExercisesResponse.setName(name);
        return this;
    }

    public AllExercisesResponseBuilder caloryCount(String caloryCount) {
        allExercisesResponse.setCaloryCount(caloryCount);
        return this;
    }

    public AllExercisesResponseBuilder category(String category) {
        allExercisesResponse.setCategory(category);
        return this;
    }

    public AllExercisesResponseBuilder cardioSubcategory(String cardioSubcategory) {
        allExercisesResponse.setCardioSubcategory(cardioSubcategory);
        return this;
    }

    public AllExercisesResponseBuilder primaryMuscleGroup(String primaryMuscleGroup) {
        allExercisesResponse.setPrimaryMuscleGroup(primaryMuscleGroup);
        return this;
    }

    public AllExercisesResponseBuilder excerciseId(String excerciseId) {
        allExercisesResponse.setExcerciseId(excerciseId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllExercisesResponse build() {
        return allExercisesResponse;
    }
}