/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllFoodRestaurantsResponseBuilder {
    //the instance to build
    private AllFoodRestaurantsResponse allFoodRestaurantsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllFoodRestaurantsResponseBuilder() {
        allFoodRestaurantsResponse = new AllFoodRestaurantsResponse();
    }

    public AllFoodRestaurantsResponseBuilder restaurantName(String restaurantName) {
        allFoodRestaurantsResponse.setRestaurantName(restaurantName);
        return this;
    }

    public AllFoodRestaurantsResponseBuilder foodRestaurantId(String foodRestaurantId) {
        allFoodRestaurantsResponse.setFoodRestaurantId(foodRestaurantId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllFoodRestaurantsResponse build() {
        return allFoodRestaurantsResponse;
    }
}