/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllFoodBrandsResponseBuilder {
    //the instance to build
    private AllFoodBrandsResponse allFoodBrandsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllFoodBrandsResponseBuilder() {
        allFoodBrandsResponse = new AllFoodBrandsResponse();
    }

    public AllFoodBrandsResponseBuilder brandName(String brandName) {
        allFoodBrandsResponse.setBrandName(brandName);
        return this;
    }

    public AllFoodBrandsResponseBuilder foodBrandId(String foodBrandId) {
        allFoodBrandsResponse.setFoodBrandId(foodBrandId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllFoodBrandsResponse build() {
        return allFoodBrandsResponse;
    }
}