/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllFoodItemsResponseBuilder {
    //the instance to build
    private AllFoodItemsResponse allFoodItemsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllFoodItemsResponseBuilder() {
        allFoodItemsResponse = new AllFoodItemsResponse();
    }

    public AllFoodItemsResponseBuilder itemName(String itemName) {
        allFoodItemsResponse.setItemName(itemName);
        return this;
    }

    public AllFoodItemsResponseBuilder calories(int calories) {
        allFoodItemsResponse.setCalories(calories);
        return this;
    }

    public AllFoodItemsResponseBuilder servingQty(double servingQty) {
        allFoodItemsResponse.setServingQty(servingQty);
        return this;
    }

    public AllFoodItemsResponseBuilder servingUnit(String servingUnit) {
        allFoodItemsResponse.setServingUnit(servingUnit);
        return this;
    }

    public AllFoodItemsResponseBuilder foodItemId(String foodItemId) {
        allFoodItemsResponse.setFoodItemId(foodItemId);
        return this;
    }

    public AllFoodItemsResponseBuilder foodBrandId(String foodBrandId) {
        allFoodItemsResponse.setFoodBrandId(foodBrandId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllFoodItemsResponse build() {
        return allFoodItemsResponse;
    }
}