/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllGenericsResponseBuilder {
    //the instance to build
    private AllGenericsResponse allGenericsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllGenericsResponseBuilder() {
        allGenericsResponse = new AllGenericsResponse();
    }

    public AllGenericsResponseBuilder name(String name) {
        allGenericsResponse.setName(name);
        return this;
    }

    public AllGenericsResponseBuilder pregnancyCategory(String pregnancyCategory) {
        allGenericsResponse.setPregnancyCategory(pregnancyCategory);
        return this;
    }

    public AllGenericsResponseBuilder lactationCategory(String lactationCategory) {
        allGenericsResponse.setLactationCategory(lactationCategory);
        return this;
    }

    public AllGenericsResponseBuilder instructions(String instructions) {
        allGenericsResponse.setInstructions(instructions);
        return this;
    }

    public AllGenericsResponseBuilder faqs(String faqs) {
        allGenericsResponse.setFaqs(faqs);
        return this;
    }

    public AllGenericsResponseBuilder genricId(int genricId) {
        allGenericsResponse.setGenricId(genricId);
        return this;
    }

    public AllGenericsResponseBuilder sideEffects(String sideEffects) {
        allGenericsResponse.setSideEffects(sideEffects);
        return this;
    }

    public AllGenericsResponseBuilder howItWorks(String howItWorks) {
        allGenericsResponse.setHowItWorks(howItWorks);
        return this;
    }

    public AllGenericsResponseBuilder therapeuticClass(String therapeuticClass) {
        allGenericsResponse.setTherapeuticClass(therapeuticClass);
        return this;
    }

    public AllGenericsResponseBuilder usedFor(String usedFor) {
        allGenericsResponse.setUsedFor(usedFor);
        return this;
    }

    public AllGenericsResponseBuilder strength(String strength) {
        allGenericsResponse.setStrength(strength);
        return this;
    }

    public AllGenericsResponseBuilder schedule(String schedule) {
        allGenericsResponse.setSchedule(schedule);
        return this;
    }

    public AllGenericsResponseBuilder alcoholInteractionDescription(String alcoholInteractionDescription) {
        allGenericsResponse.setAlcoholInteractionDescription(alcoholInteractionDescription);
        return this;
    }

    public AllGenericsResponseBuilder alcoholNteraction(boolean alcoholNteraction) {
        allGenericsResponse.setAlcoholNteraction(alcoholNteraction);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllGenericsResponse build() {
        return allGenericsResponse;
    }
}