/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AllLabTestsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4648276982356424603L;
    private String labTestName;
    private String alternateName;
    private String labTestId;
    private LabTestData34 labTestData;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_test_name")
    public String getLabTestName ( ) { 
        return this.labTestName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_test_name")
    public void setLabTestName (String value) { 
        this.labTestName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("alternate_name")
    public String getAlternateName ( ) { 
        return this.alternateName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("alternate_name")
    public void setAlternateName (String value) { 
        this.alternateName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_test_id")
    public String getLabTestId ( ) { 
        return this.labTestId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_test_id")
    public void setLabTestId (String value) { 
        this.labTestId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_test_data")
    public LabTestData34 getLabTestData ( ) { 
        return this.labTestData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_test_data")
    public void setLabTestData (LabTestData34 value) { 
        this.labTestData = value;
    }
 
}
 