/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllLabTestsResponseBuilder {
    //the instance to build
    private AllLabTestsResponse allLabTestsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllLabTestsResponseBuilder() {
        allLabTestsResponse = new AllLabTestsResponse();
    }

    public AllLabTestsResponseBuilder labTestName(String labTestName) {
        allLabTestsResponse.setLabTestName(labTestName);
        return this;
    }

    public AllLabTestsResponseBuilder alternateName(String alternateName) {
        allLabTestsResponse.setAlternateName(alternateName);
        return this;
    }

    public AllLabTestsResponseBuilder labTestId(String labTestId) {
        allLabTestsResponse.setLabTestId(labTestId);
        return this;
    }

    public AllLabTestsResponseBuilder labTestData(LabTestData34 labTestData) {
        allLabTestsResponse.setLabTestData(labTestData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllLabTestsResponse build() {
        return allLabTestsResponse;
    }
}