/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllMedicinesResponseBuilder {
    //the instance to build
    private AllMedicinesResponse allMedicinesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllMedicinesResponseBuilder() {
        allMedicinesResponse = new AllMedicinesResponse();
    }

    public AllMedicinesResponseBuilder name(String name) {
        allMedicinesResponse.setName(name);
        return this;
    }

    public AllMedicinesResponseBuilder form(String form) {
        allMedicinesResponse.setForm(form);
        return this;
    }

    public AllMedicinesResponseBuilder standardUnits(int standardUnits) {
        allMedicinesResponse.setStandardUnits(standardUnits);
        return this;
    }

    public AllMedicinesResponseBuilder packageForm(String packageForm) {
        allMedicinesResponse.setPackageForm(packageForm);
        return this;
    }

    public AllMedicinesResponseBuilder price(double price) {
        allMedicinesResponse.setPrice(price);
        return this;
    }

    public AllMedicinesResponseBuilder size(String size) {
        allMedicinesResponse.setSize(size);
        return this;
    }

    public AllMedicinesResponseBuilder manufacturer(String manufacturer) {
        allMedicinesResponse.setManufacturer(manufacturer);
        return this;
    }

    public AllMedicinesResponseBuilder constituents(List<Constituent> constituents) {
        allMedicinesResponse.setConstituents(constituents);
        return this;
    }

    public AllMedicinesResponseBuilder schedule(Schedule schedule) {
        allMedicinesResponse.setSchedule(schedule);
        return this;
    }

    public AllMedicinesResponseBuilder medicineId(String medicineId) {
        allMedicinesResponse.setMedicineId(medicineId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllMedicinesResponse build() {
        return allMedicinesResponse;
    }
}