/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AllManufacturersResponseBuilder {
    //the instance to build
    private AllManufacturersResponse allManufacturersResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllManufacturersResponseBuilder() {
        allManufacturersResponse = new AllManufacturersResponse();
    }

    public AllManufacturersResponseBuilder manufacturerId(int manufacturerId) {
        allManufacturersResponse.setManufacturerId(manufacturerId);
        return this;
    }

    public AllManufacturersResponseBuilder name(String name) {
        allManufacturersResponse.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllManufacturersResponse build() {
        return allManufacturersResponse;
    }
}