/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class AlternativeMedicinesResponseBuilder {
    //the instance to build
    private AlternativeMedicinesResponse alternativeMedicinesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AlternativeMedicinesResponseBuilder() {
        alternativeMedicinesResponse = new AlternativeMedicinesResponse();
    }

    public AlternativeMedicinesResponseBuilder name(String name) {
        alternativeMedicinesResponse.setName(name);
        return this;
    }

    public AlternativeMedicinesResponseBuilder form(String form) {
        alternativeMedicinesResponse.setForm(form);
        return this;
    }

    public AlternativeMedicinesResponseBuilder standardUnits(int standardUnits) {
        alternativeMedicinesResponse.setStandardUnits(standardUnits);
        return this;
    }

    public AlternativeMedicinesResponseBuilder packageForm(String packageForm) {
        alternativeMedicinesResponse.setPackageForm(packageForm);
        return this;
    }

    public AlternativeMedicinesResponseBuilder price(double price) {
        alternativeMedicinesResponse.setPrice(price);
        return this;
    }

    public AlternativeMedicinesResponseBuilder size(String size) {
        alternativeMedicinesResponse.setSize(size);
        return this;
    }

    public AlternativeMedicinesResponseBuilder manufacturer(String manufacturer) {
        alternativeMedicinesResponse.setManufacturer(manufacturer);
        return this;
    }

    public AlternativeMedicinesResponseBuilder constituents(List<Constituent> constituents) {
        alternativeMedicinesResponse.setConstituents(constituents);
        return this;
    }

    public AlternativeMedicinesResponseBuilder schedule(Schedule schedule) {
        alternativeMedicinesResponse.setSchedule(schedule);
        return this;
    }

    public AlternativeMedicinesResponseBuilder medicineId(String medicineId) {
        alternativeMedicinesResponse.setMedicineId(medicineId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AlternativeMedicinesResponse build() {
        return alternativeMedicinesResponse;
    }
}