/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CommonSideEffectsResponseBuilder {
    //the instance to build
    private CommonSideEffectsResponse commonSideEffectsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CommonSideEffectsResponseBuilder() {
        commonSideEffectsResponse = new CommonSideEffectsResponse();
    }

    public CommonSideEffectsResponseBuilder generic(String generic) {
        commonSideEffectsResponse.setGeneric(generic);
        return this;
    }

    public CommonSideEffectsResponseBuilder sideEffects(List<SideEffect> sideEffects) {
        commonSideEffectsResponse.setSideEffects(sideEffects);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CommonSideEffectsResponse build() {
        return commonSideEffectsResponse;
    }
}