/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CommonSideEffectsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4783312896908023383L;
    private String generic;
    private List<SideEffect> sideEffects;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("generic")
    public String getGeneric ( ) { 
        return this.generic;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("generic")
    public void setGeneric (String value) { 
        this.generic = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("side_effects")
    public List<SideEffect> getSideEffects ( ) { 
        return this.sideEffects;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("side_effects")
    public void setSideEffects (List<SideEffect> value) { 
        this.sideEffects = value;
    }
 
}
 