/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ConstituentBuilder {
    //the instance to build
    private Constituent constituent;

    /**
     * Default constructor to initialize the instance
     */
    public ConstituentBuilder() {
        constituent = new Constituent();
    }

    public ConstituentBuilder name(String name) {
        constituent.setName(name);
        return this;
    }

    public ConstituentBuilder strength(String strength) {
        constituent.setStrength(strength);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Constituent build() {
        return constituent;
    }
}