/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DiseasesResponseBuilder {
    //the instance to build
    private DiseasesResponse diseasesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public DiseasesResponseBuilder() {
        diseasesResponse = new DiseasesResponse();
    }

    public DiseasesResponseBuilder diseaseName(String diseaseName) {
        diseasesResponse.setDiseaseName(diseaseName);
        return this;
    }

    public DiseasesResponseBuilder diseaseCat(String diseaseCat) {
        diseasesResponse.setDiseaseCat(diseaseCat);
        return this;
    }

    public DiseasesResponseBuilder diseaseInfo(String diseaseInfo) {
        diseasesResponse.setDiseaseInfo(diseaseInfo);
        return this;
    }

    public DiseasesResponseBuilder diseaseId(String diseaseId) {
        diseasesResponse.setDiseaseId(diseaseId);
        return this;
    }

    public DiseasesResponseBuilder searchScore(double searchScore) {
        diseasesResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DiseasesResponse build() {
        return diseasesResponse;
    }
}