/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ExercisesResponseBuilder {
    //the instance to build
    private ExercisesResponse exercisesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ExercisesResponseBuilder() {
        exercisesResponse = new ExercisesResponse();
    }

    public ExercisesResponseBuilder name(String name) {
        exercisesResponse.setName(name);
        return this;
    }

    public ExercisesResponseBuilder category(String category) {
        exercisesResponse.setCategory(category);
        return this;
    }

    public ExercisesResponseBuilder caloryCount(String caloryCount) {
        exercisesResponse.setCaloryCount(caloryCount);
        return this;
    }

    public ExercisesResponseBuilder cardioSubcategory(String cardioSubcategory) {
        exercisesResponse.setCardioSubcategory(cardioSubcategory);
        return this;
    }

    public ExercisesResponseBuilder primaryMuscleGroup(String primaryMuscleGroup) {
        exercisesResponse.setPrimaryMuscleGroup(primaryMuscleGroup);
        return this;
    }

    public ExercisesResponseBuilder exerciseId(String exerciseId) {
        exercisesResponse.setExerciseId(exerciseId);
        return this;
    }

    public ExercisesResponseBuilder searchScore(double searchScore) {
        exercisesResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExercisesResponse build() {
        return exercisesResponse;
    }
}