/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class FoodItemsByBrandResponseBuilder {
    //the instance to build
    private FoodItemsByBrandResponse foodItemsByBrandResponse;

    /**
     * Default constructor to initialize the instance
     */
    public FoodItemsByBrandResponseBuilder() {
        foodItemsByBrandResponse = new FoodItemsByBrandResponse();
    }

    public FoodItemsByBrandResponseBuilder itemName(String itemName) {
        foodItemsByBrandResponse.setItemName(itemName);
        return this;
    }

    public FoodItemsByBrandResponseBuilder calories(int calories) {
        foodItemsByBrandResponse.setCalories(calories);
        return this;
    }

    public FoodItemsByBrandResponseBuilder servingQty(double servingQty) {
        foodItemsByBrandResponse.setServingQty(servingQty);
        return this;
    }

    public FoodItemsByBrandResponseBuilder servingUnit(String servingUnit) {
        foodItemsByBrandResponse.setServingUnit(servingUnit);
        return this;
    }

    public FoodItemsByBrandResponseBuilder foodItemId(String foodItemId) {
        foodItemsByBrandResponse.setFoodItemId(foodItemId);
        return this;
    }

    public FoodItemsByBrandResponseBuilder foodBrandId(String foodBrandId) {
        foodItemsByBrandResponse.setFoodBrandId(foodBrandId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FoodItemsByBrandResponse build() {
        return foodItemsByBrandResponse;
    }
}