/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class FoodItemsResponseBuilder {
    //the instance to build
    private FoodItemsResponse foodItemsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public FoodItemsResponseBuilder() {
        foodItemsResponse = new FoodItemsResponse();
    }

    public FoodItemsResponseBuilder calories(int calories) {
        foodItemsResponse.setCalories(calories);
        return this;
    }

    public FoodItemsResponseBuilder itemName(String itemName) {
        foodItemsResponse.setItemName(itemName);
        return this;
    }

    public FoodItemsResponseBuilder servingQty(double servingQty) {
        foodItemsResponse.setServingQty(servingQty);
        return this;
    }

    public FoodItemsResponseBuilder servingUnit(String servingUnit) {
        foodItemsResponse.setServingUnit(servingUnit);
        return this;
    }

    public FoodItemsResponseBuilder foodBrandId(String foodBrandId) {
        foodItemsResponse.setFoodBrandId(foodBrandId);
        return this;
    }

    public FoodItemsResponseBuilder foodItemId(String foodItemId) {
        foodItemsResponse.setFoodItemId(foodItemId);
        return this;
    }

    public FoodItemsResponseBuilder searchScore(double searchScore) {
        foodItemsResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FoodItemsResponse build() {
        return foodItemsResponse;
    }
}