/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class FoodItemsByRestaurantResponseBuilder {
    //the instance to build
    private FoodItemsByRestaurantResponse foodItemsByRestaurantResponse;

    /**
     * Default constructor to initialize the instance
     */
    public FoodItemsByRestaurantResponseBuilder() {
        foodItemsByRestaurantResponse = new FoodItemsByRestaurantResponse();
    }

    public FoodItemsByRestaurantResponseBuilder itemName(String itemName) {
        foodItemsByRestaurantResponse.setItemName(itemName);
        return this;
    }

    public FoodItemsByRestaurantResponseBuilder calories(int calories) {
        foodItemsByRestaurantResponse.setCalories(calories);
        return this;
    }

    public FoodItemsByRestaurantResponseBuilder servingQty(double servingQty) {
        foodItemsByRestaurantResponse.setServingQty(servingQty);
        return this;
    }

    public FoodItemsByRestaurantResponseBuilder servingUnit(String servingUnit) {
        foodItemsByRestaurantResponse.setServingUnit(servingUnit);
        return this;
    }

    public FoodItemsByRestaurantResponseBuilder foodItemId(String foodItemId) {
        foodItemsByRestaurantResponse.setFoodItemId(foodItemId);
        return this;
    }

    public FoodItemsByRestaurantResponseBuilder foodBrandId(String foodBrandId) {
        foodItemsByRestaurantResponse.setFoodBrandId(foodBrandId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FoodItemsByRestaurantResponse build() {
        return foodItemsByRestaurantResponse;
    }
}