/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class InteractionBuilder {
    //the instance to build
    private Interaction interaction;

    /**
     * Default constructor to initialize the instance
     */
    public InteractionBuilder() {
        interaction = new Interaction();
    }

    public InteractionBuilder items(List<Item> items) {
        interaction.setItems(items);
        return this;
    }

    public InteractionBuilder severity(String severity) {
        interaction.setSeverity(severity);
        return this;
    }

    public InteractionBuilder description(String description) {
        interaction.setDescription(description);
        return this;
    }

    public InteractionBuilder source(String source) {
        interaction.setSource(source);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Interaction build() {
        return interaction;
    }
}