/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ItemBuilder {
    //the instance to build
    private Item item;

    /**
     * Default constructor to initialize the instance
     */
    public ItemBuilder() {
        item = new Item();
    }

    public ItemBuilder name(String name) {
        item.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item build() {
        return item;
    }
}