/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LabTestDataBuilder {
    //the instance to build
    private LabTestData labTestData;

    /**
     * Default constructor to initialize the instance
     */
    public LabTestDataBuilder() {
        labTestData = new LabTestData();
    }

    public LabTestDataBuilder orderingInformation(String orderingInformation) {
        labTestData.setOrderingInformation(orderingInformation);
        return this;
    }

    public LabTestDataBuilder alternateNames(String alternateNames) {
        labTestData.setAlternateNames(alternateNames);
        return this;
    }

    public LabTestDataBuilder laboratory(String laboratory) {
        labTestData.setLaboratory(laboratory);
        return this;
    }

    public LabTestDataBuilder testCode(String testCode) {
        labTestData.setTestCode(testCode);
        return this;
    }

    public LabTestDataBuilder specimenTypes(String specimenTypes) {
        labTestData.setSpecimenTypes(specimenTypes);
        return this;
    }

    public LabTestDataBuilder containerTypes(String containerTypes) {
        labTestData.setContainerTypes(containerTypes);
        return this;
    }

    public LabTestDataBuilder minimumAdultVolume(String minimumAdultVolume) {
        labTestData.setMinimumAdultVolume(minimumAdultVolume);
        return this;
    }

    public LabTestDataBuilder frequency(String frequency) {
        labTestData.setFrequency(frequency);
        return this;
    }

    public LabTestDataBuilder externalLaboratory(String externalLaboratory) {
        labTestData.setExternalLaboratory(externalLaboratory);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LabTestData build() {
        return labTestData;
    }
}