/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LabTestData34Builder {
    //the instance to build
    private LabTestData34 labTestData34;

    /**
     * Default constructor to initialize the instance
     */
    public LabTestData34Builder() {
        labTestData34 = new LabTestData34();
    }

    public LabTestData34Builder orderingInformation(String orderingInformation) {
        labTestData34.setOrderingInformation(orderingInformation);
        return this;
    }

    public LabTestData34Builder laboratory(String laboratory) {
        labTestData34.setLaboratory(laboratory);
        return this;
    }

    public LabTestData34Builder testCode(String testCode) {
        labTestData34.setTestCode(testCode);
        return this;
    }

    public LabTestData34Builder specimenTypes(String specimenTypes) {
        labTestData34.setSpecimenTypes(specimenTypes);
        return this;
    }

    public LabTestData34Builder containerTypes(String containerTypes) {
        labTestData34.setContainerTypes(containerTypes);
        return this;
    }

    public LabTestData34Builder collectionInstructions(String collectionInstructions) {
        labTestData34.setCollectionInstructions(collectionInstructions);
        return this;
    }

    public LabTestData34Builder frequency(String frequency) {
        labTestData34.setFrequency(frequency);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LabTestData34 build() {
        return labTestData34;
    }
}