/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LabTestsResponseBuilder {
    //the instance to build
    private LabTestsResponse labTestsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LabTestsResponseBuilder() {
        labTestsResponse = new LabTestsResponse();
    }

    public LabTestsResponseBuilder alternateName(String alternateName) {
        labTestsResponse.setAlternateName(alternateName);
        return this;
    }

    public LabTestsResponseBuilder labTestData(LabTestData labTestData) {
        labTestsResponse.setLabTestData(labTestData);
        return this;
    }

    public LabTestsResponseBuilder labTestId(String labTestId) {
        labTestsResponse.setLabTestId(labTestId);
        return this;
    }

    public LabTestsResponseBuilder labTestName(String labTestName) {
        labTestsResponse.setLabTestName(labTestName);
        return this;
    }

    public LabTestsResponseBuilder id(String id) {
        labTestsResponse.setId(id);
        return this;
    }

    public LabTestsResponseBuilder searchScore(double searchScore) {
        labTestsResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LabTestsResponse build() {
        return labTestsResponse;
    }
}