/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MedicineInteractionsResponseBuilder {
    //the instance to build
    private MedicineInteractionsResponse medicineInteractionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MedicineInteractionsResponseBuilder() {
        medicineInteractionsResponse = new MedicineInteractionsResponse();
    }

    public MedicineInteractionsResponseBuilder generic(String generic) {
        medicineInteractionsResponse.setGeneric(generic);
        return this;
    }

    public MedicineInteractionsResponseBuilder interactions(List<Interaction> interactions) {
        medicineInteractionsResponse.setInteractions(interactions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MedicineInteractionsResponse build() {
        return medicineInteractionsResponse;
    }
}