/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MedicinesResponseBuilder {
    //the instance to build
    private MedicinesResponse medicinesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MedicinesResponseBuilder() {
        medicinesResponse = new MedicinesResponse();
    }

    public MedicinesResponseBuilder name(String name) {
        medicinesResponse.setName(name);
        return this;
    }

    public MedicinesResponseBuilder form(String form) {
        medicinesResponse.setForm(form);
        return this;
    }

    public MedicinesResponseBuilder standardUnits(int standardUnits) {
        medicinesResponse.setStandardUnits(standardUnits);
        return this;
    }

    public MedicinesResponseBuilder packageForm(String packageForm) {
        medicinesResponse.setPackageForm(packageForm);
        return this;
    }

    public MedicinesResponseBuilder price(double price) {
        medicinesResponse.setPrice(price);
        return this;
    }

    public MedicinesResponseBuilder size(String size) {
        medicinesResponse.setSize(size);
        return this;
    }

    public MedicinesResponseBuilder manufacturer(String manufacturer) {
        medicinesResponse.setManufacturer(manufacturer);
        return this;
    }

    public MedicinesResponseBuilder constituents(List<Constituent> constituents) {
        medicinesResponse.setConstituents(constituents);
        return this;
    }

    public MedicinesResponseBuilder schedule(Schedule schedule) {
        medicinesResponse.setSchedule(schedule);
        return this;
    }

    public MedicinesResponseBuilder id(String id) {
        medicinesResponse.setId(id);
        return this;
    }

    public MedicinesResponseBuilder medicineId(String medicineId) {
        medicinesResponse.setMedicineId(medicineId);
        return this;
    }

    public MedicinesResponseBuilder searchScore(double searchScore) {
        medicinesResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MedicinesResponse build() {
        return medicinesResponse;
    }
}