/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MedicinesByGenericResponseBuilder {
    //the instance to build
    private MedicinesByGenericResponse medicinesByGenericResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MedicinesByGenericResponseBuilder() {
        medicinesByGenericResponse = new MedicinesByGenericResponse();
    }

    public MedicinesByGenericResponseBuilder name(String name) {
        medicinesByGenericResponse.setName(name);
        return this;
    }

    public MedicinesByGenericResponseBuilder form(String form) {
        medicinesByGenericResponse.setForm(form);
        return this;
    }

    public MedicinesByGenericResponseBuilder standardUnits(int standardUnits) {
        medicinesByGenericResponse.setStandardUnits(standardUnits);
        return this;
    }

    public MedicinesByGenericResponseBuilder packageForm(String packageForm) {
        medicinesByGenericResponse.setPackageForm(packageForm);
        return this;
    }

    public MedicinesByGenericResponseBuilder price(double price) {
        medicinesByGenericResponse.setPrice(price);
        return this;
    }

    public MedicinesByGenericResponseBuilder size(String size) {
        medicinesByGenericResponse.setSize(size);
        return this;
    }

    public MedicinesByGenericResponseBuilder manufacturer(String manufacturer) {
        medicinesByGenericResponse.setManufacturer(manufacturer);
        return this;
    }

    public MedicinesByGenericResponseBuilder constituents(List<Constituent> constituents) {
        medicinesByGenericResponse.setConstituents(constituents);
        return this;
    }

    public MedicinesByGenericResponseBuilder schedule(Schedule schedule) {
        medicinesByGenericResponse.setSchedule(schedule);
        return this;
    }

    public MedicinesByGenericResponseBuilder medicineId(String medicineId) {
        medicinesByGenericResponse.setMedicineId(medicineId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MedicinesByGenericResponse build() {
        return medicinesByGenericResponse;
    }
}