/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MedicinesByManufacturerResponseBuilder {
    //the instance to build
    private MedicinesByManufacturerResponse medicinesByManufacturerResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MedicinesByManufacturerResponseBuilder() {
        medicinesByManufacturerResponse = new MedicinesByManufacturerResponse();
    }

    public MedicinesByManufacturerResponseBuilder name(String name) {
        medicinesByManufacturerResponse.setName(name);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder form(String form) {
        medicinesByManufacturerResponse.setForm(form);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder standardUnits(int standardUnits) {
        medicinesByManufacturerResponse.setStandardUnits(standardUnits);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder packageForm(String packageForm) {
        medicinesByManufacturerResponse.setPackageForm(packageForm);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder price(double price) {
        medicinesByManufacturerResponse.setPrice(price);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder size(String size) {
        medicinesByManufacturerResponse.setSize(size);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder manufacturer(String manufacturer) {
        medicinesByManufacturerResponse.setManufacturer(manufacturer);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder constituents(List<Constituent> constituents) {
        medicinesByManufacturerResponse.setConstituents(constituents);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder schedule(Schedule schedule) {
        medicinesByManufacturerResponse.setSchedule(schedule);
        return this;
    }

    public MedicinesByManufacturerResponseBuilder medicineId(String medicineId) {
        medicinesByManufacturerResponse.setMedicineId(medicineId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MedicinesByManufacturerResponse build() {
        return medicinesByManufacturerResponse;
    }
}