/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PopularUsageResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5647646359799166165L;
    private String generic;
    private List<Usage> usages;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("generic")
    public String getGeneric ( ) { 
        return this.generic;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("generic")
    public void setGeneric (String value) { 
        this.generic = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usages")
    public List<Usage> getUsages ( ) { 
        return this.usages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usages")
    public void setUsages (List<Usage> value) { 
        this.usages = value;
    }
 
}
 