/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class PopularUsageResponseBuilder {
    //the instance to build
    private PopularUsageResponse popularUsageResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PopularUsageResponseBuilder() {
        popularUsageResponse = new PopularUsageResponse();
    }

    public PopularUsageResponseBuilder generic(String generic) {
        popularUsageResponse.setGeneric(generic);
        return this;
    }

    public PopularUsageResponseBuilder usages(List<Usage> usages) {
        popularUsageResponse.setUsages(usages);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PopularUsageResponse build() {
        return popularUsageResponse;
    }
}