/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class RequestAccessTokenRequestBuilder {
    //the instance to build
    private RequestAccessTokenRequest requestAccessTokenRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RequestAccessTokenRequestBuilder() {
        requestAccessTokenRequest = new RequestAccessTokenRequest();
    }

    public RequestAccessTokenRequestBuilder grantType(String grantType) {
        requestAccessTokenRequest.setGrantType(grantType);
        return this;
    }

    public RequestAccessTokenRequestBuilder clientId(String clientId) {
        requestAccessTokenRequest.setClientId(clientId);
        return this;
    }

    public RequestAccessTokenRequestBuilder clientSecret(String clientSecret) {
        requestAccessTokenRequest.setClientSecret(clientSecret);
        return this;
    }

    public RequestAccessTokenRequestBuilder scope(String scope) {
        requestAccessTokenRequest.setScope(scope);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RequestAccessTokenRequest build() {
        return requestAccessTokenRequest;
    }
}