/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ScheduleBuilder {
    //the instance to build
    private Schedule schedule;

    /**
     * Default constructor to initialize the instance
     */
    public ScheduleBuilder() {
        schedule = new Schedule();
    }

    public ScheduleBuilder category(String category) {
        schedule.setCategory(category);
        return this;
    }

    public ScheduleBuilder label(String label) {
        schedule.setLabel(label);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Schedule build() {
        return schedule;
    }
}