/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchFoodRestaurantsResponseBuilder {
    //the instance to build
    private SearchFoodRestaurantsResponse searchFoodRestaurantsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchFoodRestaurantsResponseBuilder() {
        searchFoodRestaurantsResponse = new SearchFoodRestaurantsResponse();
    }

    public SearchFoodRestaurantsResponseBuilder logo(String logo) {
        searchFoodRestaurantsResponse.setLogo(logo);
        return this;
    }

    public SearchFoodRestaurantsResponseBuilder name(String name) {
        searchFoodRestaurantsResponse.setName(name);
        return this;
    }

    public SearchFoodRestaurantsResponseBuilder foodRestaurantId(String foodRestaurantId) {
        searchFoodRestaurantsResponse.setFoodRestaurantId(foodRestaurantId);
        return this;
    }

    public SearchFoodRestaurantsResponseBuilder searchScore(double searchScore) {
        searchFoodRestaurantsResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchFoodRestaurantsResponse build() {
        return searchFoodRestaurantsResponse;
    }
}