/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchLabTestsResponseBuilder {
    //the instance to build
    private SearchLabTestsResponse searchLabTestsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchLabTestsResponseBuilder() {
        searchLabTestsResponse = new SearchLabTestsResponse();
    }

    public SearchLabTestsResponseBuilder alternateName(String alternateName) {
        searchLabTestsResponse.setAlternateName(alternateName);
        return this;
    }

    public SearchLabTestsResponseBuilder labTestData(LabTestData labTestData) {
        searchLabTestsResponse.setLabTestData(labTestData);
        return this;
    }

    public SearchLabTestsResponseBuilder labTestId(String labTestId) {
        searchLabTestsResponse.setLabTestId(labTestId);
        return this;
    }

    public SearchLabTestsResponseBuilder labTestName(String labTestName) {
        searchLabTestsResponse.setLabTestName(labTestName);
        return this;
    }

    public SearchLabTestsResponseBuilder id(String id) {
        searchLabTestsResponse.setId(id);
        return this;
    }

    public SearchLabTestsResponseBuilder searchScore(double searchScore) {
        searchLabTestsResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchLabTestsResponse build() {
        return searchLabTestsResponse;
    }
}