/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchFoodBrandsResponseBuilder {
    //the instance to build
    private SearchFoodBrandsResponse searchFoodBrandsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchFoodBrandsResponseBuilder() {
        searchFoodBrandsResponse = new SearchFoodBrandsResponse();
    }

    public SearchFoodBrandsResponseBuilder logo(String logo) {
        searchFoodBrandsResponse.setLogo(logo);
        return this;
    }

    public SearchFoodBrandsResponseBuilder name(String name) {
        searchFoodBrandsResponse.setName(name);
        return this;
    }

    public SearchFoodBrandsResponseBuilder foodBrandId(String foodBrandId) {
        searchFoodBrandsResponse.setFoodBrandId(foodBrandId);
        return this;
    }

    public SearchFoodBrandsResponseBuilder searchScore(double searchScore) {
        searchFoodBrandsResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchFoodBrandsResponse build() {
        return searchFoodBrandsResponse;
    }
}