/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchDiseasesResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5178111129544073156L;
    private String diseaseName;
    private String diseaseCat;
    private String diseaseInfo;
    private String diseaseId;
    private double searchScore;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disease_name")
    public String getDiseaseName ( ) { 
        return this.diseaseName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disease_name")
    public void setDiseaseName (String value) { 
        this.diseaseName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disease_cat")
    public String getDiseaseCat ( ) { 
        return this.diseaseCat;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disease_cat")
    public void setDiseaseCat (String value) { 
        this.diseaseCat = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disease_info")
    public String getDiseaseInfo ( ) { 
        return this.diseaseInfo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disease_info")
    public void setDiseaseInfo (String value) { 
        this.diseaseInfo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disease_id")
    public String getDiseaseId ( ) { 
        return this.diseaseId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disease_id")
    public void setDiseaseId (String value) { 
        this.diseaseId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("search_score")
    public double getSearchScore ( ) { 
        return this.searchScore;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("search_score")
    public void setSearchScore (double value) { 
        this.searchScore = value;
    }
 
}
 