/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchManufacturersResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5643504533472236734L;
    private int manufacturerId;
    private String name;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("manufacturer_id")
    public int getManufacturerId ( ) { 
        return this.manufacturerId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("manufacturer_id")
    public void setManufacturerId (int value) { 
        this.manufacturerId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
}
 