/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchExercisesResponseBuilder {
    //the instance to build
    private SearchExercisesResponse searchExercisesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchExercisesResponseBuilder() {
        searchExercisesResponse = new SearchExercisesResponse();
    }

    public SearchExercisesResponseBuilder name(String name) {
        searchExercisesResponse.setName(name);
        return this;
    }

    public SearchExercisesResponseBuilder category(String category) {
        searchExercisesResponse.setCategory(category);
        return this;
    }

    public SearchExercisesResponseBuilder caloryCount(String caloryCount) {
        searchExercisesResponse.setCaloryCount(caloryCount);
        return this;
    }

    public SearchExercisesResponseBuilder cardioSubcategory(String cardioSubcategory) {
        searchExercisesResponse.setCardioSubcategory(cardioSubcategory);
        return this;
    }

    public SearchExercisesResponseBuilder primaryMuscleGroup(String primaryMuscleGroup) {
        searchExercisesResponse.setPrimaryMuscleGroup(primaryMuscleGroup);
        return this;
    }

    public SearchExercisesResponseBuilder excerciseId(String excerciseId) {
        searchExercisesResponse.setExcerciseId(excerciseId);
        return this;
    }

    public SearchExercisesResponseBuilder searchScore(double searchScore) {
        searchExercisesResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchExercisesResponse build() {
        return searchExercisesResponse;
    }
}