/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchMedicinesResponseBuilder {
    //the instance to build
    private SearchMedicinesResponse searchMedicinesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchMedicinesResponseBuilder() {
        searchMedicinesResponse = new SearchMedicinesResponse();
    }

    public SearchMedicinesResponseBuilder name(String name) {
        searchMedicinesResponse.setName(name);
        return this;
    }

    public SearchMedicinesResponseBuilder form(String form) {
        searchMedicinesResponse.setForm(form);
        return this;
    }

    public SearchMedicinesResponseBuilder standardUnits(int standardUnits) {
        searchMedicinesResponse.setStandardUnits(standardUnits);
        return this;
    }

    public SearchMedicinesResponseBuilder packageForm(String packageForm) {
        searchMedicinesResponse.setPackageForm(packageForm);
        return this;
    }

    public SearchMedicinesResponseBuilder price(double price) {
        searchMedicinesResponse.setPrice(price);
        return this;
    }

    public SearchMedicinesResponseBuilder size(String size) {
        searchMedicinesResponse.setSize(size);
        return this;
    }

    public SearchMedicinesResponseBuilder manufacturer(String manufacturer) {
        searchMedicinesResponse.setManufacturer(manufacturer);
        return this;
    }

    public SearchMedicinesResponseBuilder constituents(List<Constituent> constituents) {
        searchMedicinesResponse.setConstituents(constituents);
        return this;
    }

    public SearchMedicinesResponseBuilder schedule(Schedule schedule) {
        searchMedicinesResponse.setSchedule(schedule);
        return this;
    }

    public SearchMedicinesResponseBuilder id(String id) {
        searchMedicinesResponse.setId(id);
        return this;
    }

    public SearchMedicinesResponseBuilder medicineId(String medicineId) {
        searchMedicinesResponse.setMedicineId(medicineId);
        return this;
    }

    public SearchMedicinesResponseBuilder searchScore(double searchScore) {
        searchMedicinesResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchMedicinesResponse build() {
        return searchMedicinesResponse;
    }
}