/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchFoodBrandsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5353411624786343679L;
    private String logo;
    private String name;
    private String foodBrandId;
    private double searchScore;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("logo")
    public String getLogo ( ) { 
        return this.logo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("logo")
    public void setLogo (String value) { 
        this.logo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("food_brand_id")
    public String getFoodBrandId ( ) { 
        return this.foodBrandId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("food_brand_id")
    public void setFoodBrandId (String value) { 
        this.foodBrandId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("search_score")
    public double getSearchScore ( ) { 
        return this.searchScore;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("search_score")
    public void setSearchScore (double value) { 
        this.searchScore = value;
    }
 
}
 