/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchDiseasesResponseBuilder {
    //the instance to build
    private SearchDiseasesResponse searchDiseasesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchDiseasesResponseBuilder() {
        searchDiseasesResponse = new SearchDiseasesResponse();
    }

    public SearchDiseasesResponseBuilder diseaseName(String diseaseName) {
        searchDiseasesResponse.setDiseaseName(diseaseName);
        return this;
    }

    public SearchDiseasesResponseBuilder diseaseCat(String diseaseCat) {
        searchDiseasesResponse.setDiseaseCat(diseaseCat);
        return this;
    }

    public SearchDiseasesResponseBuilder diseaseInfo(String diseaseInfo) {
        searchDiseasesResponse.setDiseaseInfo(diseaseInfo);
        return this;
    }

    public SearchDiseasesResponseBuilder diseaseId(String diseaseId) {
        searchDiseasesResponse.setDiseaseId(diseaseId);
        return this;
    }

    public SearchDiseasesResponseBuilder searchScore(double searchScore) {
        searchDiseasesResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchDiseasesResponse build() {
        return searchDiseasesResponse;
    }
}