/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchExercisesResponse16Builder {
    //the instance to build
    private SearchExercisesResponse16 searchExercisesResponse16;

    /**
     * Default constructor to initialize the instance
     */
    public SearchExercisesResponse16Builder() {
        searchExercisesResponse16 = new SearchExercisesResponse16();
    }

    public SearchExercisesResponse16Builder name(String name) {
        searchExercisesResponse16.setName(name);
        return this;
    }

    public SearchExercisesResponse16Builder category(String category) {
        searchExercisesResponse16.setCategory(category);
        return this;
    }

    public SearchExercisesResponse16Builder caloryCount(String caloryCount) {
        searchExercisesResponse16.setCaloryCount(caloryCount);
        return this;
    }

    public SearchExercisesResponse16Builder cardioSubcategory(String cardioSubcategory) {
        searchExercisesResponse16.setCardioSubcategory(cardioSubcategory);
        return this;
    }

    public SearchExercisesResponse16Builder primaryMuscleGroup(String primaryMuscleGroup) {
        searchExercisesResponse16.setPrimaryMuscleGroup(primaryMuscleGroup);
        return this;
    }

    public SearchExercisesResponse16Builder exerciseId(String exerciseId) {
        searchExercisesResponse16.setExerciseId(exerciseId);
        return this;
    }

    public SearchExercisesResponse16Builder searchScore(double searchScore) {
        searchExercisesResponse16.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchExercisesResponse16 build() {
        return searchExercisesResponse16;
    }
}