/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchFoodItemsResponseBuilder {
    //the instance to build
    private SearchFoodItemsResponse searchFoodItemsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchFoodItemsResponseBuilder() {
        searchFoodItemsResponse = new SearchFoodItemsResponse();
    }

    public SearchFoodItemsResponseBuilder calories(int calories) {
        searchFoodItemsResponse.setCalories(calories);
        return this;
    }

    public SearchFoodItemsResponseBuilder itemName(String itemName) {
        searchFoodItemsResponse.setItemName(itemName);
        return this;
    }

    public SearchFoodItemsResponseBuilder servingQty(double servingQty) {
        searchFoodItemsResponse.setServingQty(servingQty);
        return this;
    }

    public SearchFoodItemsResponseBuilder servingUnit(String servingUnit) {
        searchFoodItemsResponse.setServingUnit(servingUnit);
        return this;
    }

    public SearchFoodItemsResponseBuilder foodBrandId(String foodBrandId) {
        searchFoodItemsResponse.setFoodBrandId(foodBrandId);
        return this;
    }

    public SearchFoodItemsResponseBuilder foodItemId(String foodItemId) {
        searchFoodItemsResponse.setFoodItemId(foodItemId);
        return this;
    }

    public SearchFoodItemsResponseBuilder searchScore(double searchScore) {
        searchFoodItemsResponse.setSearchScore(searchScore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchFoodItemsResponse build() {
        return searchFoodItemsResponse;
    }
}