/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SearchManufacturersResponseBuilder {
    //the instance to build
    private SearchManufacturersResponse searchManufacturersResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchManufacturersResponseBuilder() {
        searchManufacturersResponse = new SearchManufacturersResponse();
    }

    public SearchManufacturersResponseBuilder manufacturerId(int manufacturerId) {
        searchManufacturersResponse.setManufacturerId(manufacturerId);
        return this;
    }

    public SearchManufacturersResponseBuilder name(String name) {
        searchManufacturersResponse.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchManufacturersResponse build() {
        return searchManufacturersResponse;
    }
}