/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SideEffectBuilder {
    //the instance to build
    private SideEffect sideEffect;

    /**
     * Default constructor to initialize the instance
     */
    public SideEffectBuilder() {
        sideEffect = new SideEffect();
    }

    public SideEffectBuilder term(String term) {
        sideEffect.setTerm(term);
        return this;
    }

    public SideEffectBuilder count(int count) {
        sideEffect.setCount(count);
        return this;
    }

    public SideEffectBuilder percent(double percent) {
        sideEffect.setPercent(percent);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SideEffect build() {
        return sideEffect;
    }
}