/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SimilarMedicinesResponseBuilder {
    //the instance to build
    private SimilarMedicinesResponse similarMedicinesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarMedicinesResponseBuilder() {
        similarMedicinesResponse = new SimilarMedicinesResponse();
    }

    public SimilarMedicinesResponseBuilder name(String name) {
        similarMedicinesResponse.setName(name);
        return this;
    }

    public SimilarMedicinesResponseBuilder form(String form) {
        similarMedicinesResponse.setForm(form);
        return this;
    }

    public SimilarMedicinesResponseBuilder standardUnits(int standardUnits) {
        similarMedicinesResponse.setStandardUnits(standardUnits);
        return this;
    }

    public SimilarMedicinesResponseBuilder packageForm(String packageForm) {
        similarMedicinesResponse.setPackageForm(packageForm);
        return this;
    }

    public SimilarMedicinesResponseBuilder price(double price) {
        similarMedicinesResponse.setPrice(price);
        return this;
    }

    public SimilarMedicinesResponseBuilder size(String size) {
        similarMedicinesResponse.setSize(size);
        return this;
    }

    public SimilarMedicinesResponseBuilder manufacturer(String manufacturer) {
        similarMedicinesResponse.setManufacturer(manufacturer);
        return this;
    }

    public SimilarMedicinesResponseBuilder constituents(List<Constituent> constituents) {
        similarMedicinesResponse.setConstituents(constituents);
        return this;
    }

    public SimilarMedicinesResponseBuilder schedule(Schedule schedule) {
        similarMedicinesResponse.setSchedule(schedule);
        return this;
    }

    public SimilarMedicinesResponseBuilder medicineId(String medicineId) {
        similarMedicinesResponse.setMedicineId(medicineId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarMedicinesResponse build() {
        return similarMedicinesResponse;
    }
}