/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class UsageBuilder {
    //the instance to build
    private Usage usage;

    /**
     * Default constructor to initialize the instance
     */
    public UsageBuilder() {
        usage = new Usage();
    }

    public UsageBuilder term(String term) {
        usage.setTerm(term);
        return this;
    }

    public UsageBuilder count(int count) {
        usage.setCount(count);
        return this;
    }

    public UsageBuilder percent(double percent) {
        usage.setPercent(percent);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Usage build() {
        return usage;
    }
}