/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://{%1$s}/api/v1";

    //TODO: Replace the host with an appropriate value
    public static String host = "TODO: Replace";

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "TODO: Replace";

}
